services:
  - type: web
    name: docrh
    env: python
    build:
      buildCommand: pip install -r requirements.txt
      buildpacks:
        - https://github.com/render-examples/poppler-buildpack.git
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
